import Head from 'next/head'
import { Inter } from 'next/font/google'
import Layouts from '@/components/Layouts'
import Image from 'next/image'
import profilePic from '../../public/images/profile/developer-pic-1.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import Skills from './Skills'
import Experience from '@/components/Experience'
import Education from '@/components/Education'
import React from 'react'
import Typed from 'typed.js'

const inter = Inter({ subsets: ['latin'] })


function TypedComponent() {
  // Create reference to store the DOM element containing the animation
  const el = React.useRef(null);

  React.useEffect(() => {
    const typed = new Typed(el.current, {
      strings: ['Full Stack Software Engineer.', 'Front End Developer.', 'Back End Developer.'],
      typeSpeed: 100,
      backSpeed: 50,
      loop: true,
    });

    return () => {
      // Destroy Typed instance during cleanup to stop animation
      typed.destroy();
    };
  }, []);

  return (
    <div className="App">
      <style jsx>{`
        .typed-cursor {
          font-size: inherit; /* Set the cursor size to inherit from the parent font size */
        }
      `}</style>
      <span ref={el} className="text-6xl font-bold" /> {/* Apply Tailwind classes */}
    </div>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title> John Agni | Full Stack Web Developer </title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layouts className='pt-0'>
          <div className="flex items-center justify-between w-full">
            <div className='w-1/2'>
              <Image src={profilePic} alt="CodeBucks" className='w-full h-auto' />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <div className='text-4xl font-bold text-6xl'>Hi! I'm John Agni the...</div>

              {/* <AnimatedText text="Hi! I'm John Agni the..." className='!text-6xl !text-left'/> */}
              <TypedComponent />


              <p className='my-4 text-base font-medium'>As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications.
Explore my latest projects and articles, showcasing my expertise in React.js and web development.
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link href="/dummy.pdf" target={"_blank"} className="flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark" download={true}> <LinkArrow className={"w-6 ml-1"} /> Resume</Link>
                <Link href="mailto:johncliffordagni@gmail.com" className="ml-4 text-lg font-medium capitalize text-dark underline">Contact</Link>
              </div>
            </div>
          </div>
          <Skills />
          <Experience />
          <Education />
        </Layouts>

        <HireMe />
      </main>
    </>
  )
}
